longhorn:
  image:
    longhorn:
      engine:
        repository: longhornio/longhorn-engine
        tag: v1.5.2
      manager:
        repository: longhornio/longhorn-manager
        tag: v1.5.2
      ui:
        repository: longhornio/longhorn-ui
        tag: v1.5.2
      instanceManager:
        repository: longhornio/longhorn-instance-manager
        tag: v1.5.2
      shareManager:
        repository: longhornio/longhorn-share-manager
        tag: v1.5.2
      backingImageManager:
        repository: longhornio/backing-image-manager
        tag: v1.5.2
      supportBundleKit:
        repository: longhornio/support-bundle-kit
        tag: v0.0.27
    pullPolicy: IfNotPresent

  service:
    ui:
      type: ClusterIP
    manager:
      type: ClusterIP

  # Set to true after the first installation
  helmPreUpgradeCheckerJob:
    enabled: false
