argo-cd:
  fullnameOverride: argocd

  redis-ha:
    enabled: true

  controller:
    replicas: 1

  server:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3

    extraArgs:
      - --insecure

    ingress:
      enabled: true
      hosts:
        - argocd.davidgrundstrom.se
      paths:
        - /
      pathType: Prefix
    
    service:
      type: LoadBalancer
    

  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3

  applicationSet:
    replicas: 2
